url: https://bsankaran.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Home
email: bharath@scaledrobotics.com
description: "Personal website for Bharath Sankaran. CTO and Co-founder of Scaled Robotics. Expert in Robotics, 3D Perception and Machine Learning"


# Team names, titles and social links
people:
- name: Argentine Tango
  pic: 1
- name: Rock Climbing
  pic: 2
- name: Outreach
  pic: 3

  # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/BharathSankara1
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/scaledrobotics
  - title: github
    url: http://github.com/bsankaran

# Postal address (add as many lines as necessary)
address:
  - line: C/ Pere IV 29, 6-6A
  - line: Barcelona, ES-08018
markdown: kramdown
permalink: pretty
